name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Se ejecuta cuando hay un push en la rama 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Ejecuta el job en un runner de Ubuntu
    environment: production # Usa los secretos del environment 'production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Descarga el código del repositorio

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Habilita Docker Buildx para la construcción de imágenes

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Inicia sesión en Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Usuario de Docker Hub
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Token de acceso

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Usa el directorio actual como contexto de construcción
          file: ./Dockerfile # Especifica el Dockerfile a usar
          push: true # Indica que la imagen debe ser subida a Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-test:latest # Etiqueta la imagen con el nombre de usuario y 'latest'
